DROP TABLE review;
DROP TABLE notice;
DROP TABLE qna_answer;
DROP TABLE qna;
DROP TABLE user;
DROP TABLE collect;


CREATE TABLE user(
    id VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
	name VARCHAR(20) NOT NULL,
	phone VARCHAR(13) NOT NULL UNIQUE,
	post_code INT NOT NULL,
	road_address VARCHAR(30) NOT NULL,
	detail_address VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	bank_name VARCHAR(20) NOT NULL,
	account VARCHAR(20) NOT NULL,
    auth VARCHAR(10) DEFAULT 'MEMBER',
    enabled INT DEFAULT 1
);

CREATE TABLE collect(
order_num INT PRIMARY KEY AUTO_INCREMENT,
id VARCHAR(20),
name VARCHAR(20) NOT NULL,
phone VARCHAR(13) NOT NULL,
post_code INT NOT NULL,
road_address VARCHAR(30) NOT NULL,
detail_address VARCHAR(30) NOT NULL,
collection_date DATE NOT NULL,
door_pwd  VARCHAR(30),           
request TEXT,
prog VARCHAR(30) DEFAULT '신청완료',
kg INT NOT NULL
);

CREATE TABLE review (
no INT PRIMARY KEY AUTO_INCREMENT,
id VARCHAR(20) NOT NULL,		
title VARCHAR(30) NOT NULL,
content TEXT NOT NULL,	
order_num INT,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
url VARCHAR(200),
rating INT
);
   
CREATE TABLE qna (
qna_num INT PRIMARY KEY AUTO_INCREMENT,
id VARCHAR(20) NOT NULL,
title VARCHAR(30) NOT NULL,
content TEXT NOT NULL,
write_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
url VARCHAR(200),
status CHAR(1) CHECK(status IN('Y','N')) DEFAULT 'N'
);

CREATE TABLE qna_answer(
qna_num INT NOT NULL,
id VARCHAR(20) NOT NULL,
content TEXT NOT NULL,
url VARCHAR(200),
answer_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE notice(
notice_num INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(30) NOT NULL,
content TEXT NOT NULL,
id VARCHAR(30),
url VARCHAR(200),
write_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



ALTER TABLE review ADD CONSTRAINT revi_cust_id
	FOREIGN KEY (id) REFERENCES user(id) ON DELETE CASCADE;
ALTER TABLE qna ADD CONSTRAINT qna_cust_id
	FOREIGN KEY (id) REFERENCES user(id) ON DELETE CASCADE;

ALTER TABLE review ADD CONSTRAINT rev_order_num
	FOREIGN KEY (order_num) REFERENCES collect(order_num) ON DELETE CASCADE;
ALTER TABLE qna ADD CONSTRAINT qna_order_num
	FOREIGN KEY (order_num) REFERENCES collect(order_num) ON DELETE CASCADE;
    
ALTER TABLE qna_answer ADD CONSTRAINT qna_num
	FOREIGN KEY (qna_num) REFERENCES qna(qna_num) ON DELETE CASCADE;
